In [10]:
from scipy import *
import scipy.linalg as la
import numpy as np

In [11]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [13]:
c = la.lstsq(A,b)
c

(array([-0.22222222,  0.11111111,  0.44444444]),
 array([], dtype=float64),
 2,
 array([1.42267074e+01, 1.26522599e+00, 4.97902781e-16]))

In [14]:
d = np.matmul(A, c[0])
d

array([1., 2., 3.])

In [25]:
B = np.random.randint(10, size=[3,3])
print(B)
e1 = la.lstsq(A,B)
e2 = np.matmul(A,e1[0])
e2

[[1 8 1]
 [6 8 1]
 [0 7 0]]


array([[2.83333333, 8.16666667, 1.16666667],
       [2.33333333, 7.66666667, 0.66666667],
       [1.83333333, 7.16666667, 0.16666667]])

In [26]:
f = la.eig(A)
f

(array([ 1.33484692e+01+0.j, -1.34846923e+00+0.j, -1.15433316e-15+0.j]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

In [28]:
g1 = la.inv(B)
g2 = la.det(B)
g1, g2

(array([[-2.00000000e-01,  2.00000000e-01,  6.34413157e-18],
        [-0.00000000e+00,  0.00000000e+00,  1.42857143e-01],
        [ 1.20000000e+00, -2.00000000e-01, -1.14285714e+00]]),
 35.0)

In [29]:
h = la.norm(A)
h

14.2828568570857